---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    driver:
      vm_hostname: zabbix-agent-cookbook-test.example.com
    attributes:
      zabbix:
        redis_conf: '/etc/redis/redis_prime.conf'
      redis2:
        maxclients: '128'
        instances:
          prime:
            bindaddress: '127.0.0.1'
            requirepass: 'neko_nya_nya'
            maxclients: '128'
    run_list:
      - recipe[apt]
      - recipe[redis2::default_instance]
      - recipe[zabbix_agent_test]
      - recipe[zabbix-agent::redis]
